export type CompanySource = {
  company: string;
  segment?: string;
  url: string;
  sourceName: string;
  keywords: string[];
  matchers: string[];
  procurementKeywords?: string[];
  expoKeywords?: string[];
  preferredPathHints?: string[];
};

export const companySources: CompanySource[] = [
  {
    company: "阳光电源",
    segment: "逆变器/储能",
    sourceName: "阳光电源官网",
    url: "https://cn.sungrowpower.com/newsList",
    keywords: ["SNEC", "展会", "储能", "新品", "上海"],
    matchers: ["阳光电源", "sungrow", "snec"],
    procurementKeywords: ["招标", "采购", "供应商", "征集", "比选", "邀标"],
    expoKeywords: ["SNEC", "展会", "储能", "上海", "展台", "搭建"],
    preferredPathHints: ["news", "media", "article"],
  },
  {
    company: "晶科能源",
    segment: "光伏组件",
    sourceName: "晶科能源官网",
    url: "https://www.jinkosolar.com/news",
    keywords: ["Intersolar", "欧洲", "组件", "展会", "慕尼黑"],
    matchers: ["晶科能源", "jinkosolar", "intersolar"],
    procurementKeywords: ["招标", "采购", "tender", "rfp", "vendor"],
    expoKeywords: ["Intersolar", "Europe", "展会", "慕尼黑", "组件"],
    preferredPathHints: ["news", "press", "media"],
  },
  {
    company: "宁德时代",
    segment: "储能/动力电池",
    sourceName: "宁德时代官网",
    url: "https://www.catl.com/news/",
    keywords: ["储能", "展会", "论坛", "发布", "电池"],
    matchers: ["宁德时代", "catl", "储能"],
    procurementKeywords: ["招标", "采购", "供应商", "框架", "入库"],
    expoKeywords: ["储能", "展会", "论坛", "电池", "发布"],
    preferredPathHints: ["news", "media", "press"],
  },
  {
    company: "隆基绿能",
    segment: "光伏组件",
    sourceName: "隆基官网",
    url: "https://www.longi.com/cn/news/",
    keywords: ["SNEC", "BC", "氢能", "展会", "发布"],
    matchers: ["隆基", "longi", "snec"],
    procurementKeywords: ["招标", "采购", "供应商", "搭建", "征集"],
    expoKeywords: ["SNEC", "BC", "氢能", "展会", "展台", "搭建"],
    preferredPathHints: ["news", "media", "press"],
  },
  {
    company: "特隆美",
    segment: "储能系统",
    sourceName: "特隆美官网",
    url: "https://www.tecloman.com/news",
    keywords: ["Smarter E", "SNEC", "储能", "展会", "慕尼黑"],
    matchers: ["特隆美", "tecloman", "smarter e", "snec"],
    procurementKeywords: ["招标", "采购", "邀标", "竞标", "搭建"],
    expoKeywords: ["Smarter E", "SNEC", "储能", "展会", "慕尼黑", "搭建"],
    preferredPathHints: ["news", "media", "article"],
  },
  {
    company: "海辰储能",
    segment: "储能电芯",
    sourceName: "海辰储能官网",
    url: "https://www.hithium.com/news",
    keywords: ["SNEC", "储能", "电芯", "展会", "发布"],
    matchers: ["海辰", "hithium", "snec"],
    procurementKeywords: ["招标", "比选", "采购", "供应商"],
    expoKeywords: ["SNEC", "储能", "电芯", "展会", "发布"],
    preferredPathHints: ["news", "media", "press"],
  },
  {
    company: "比亚迪储能",
    segment: "储能系统",
    sourceName: "比亚迪官网",
    url: "https://www.byd.com/cn/news",
    keywords: ["储能", "欧洲", "ees", "展会", "发布"],
    matchers: ["比亚迪", "byd", "ees europe"],
    procurementKeywords: ["招标", "采购", "供应商", "邀标"],
    expoKeywords: ["储能", "ees", "Europe", "展会", "发布"],
    preferredPathHints: ["news", "media", "press"],
  },
  {
    company: "固德威",
    segment: "逆变器",
    sourceName: "固德威官网",
    url: "https://en.goodwe.com/news",
    keywords: ["Intersolar", "欧洲", "逆变器", "展会", "户用"],
    matchers: ["固德威", "goodwe", "intersolar"],
    procurementKeywords: ["tender", "procurement", "vendor", "招标"],
    expoKeywords: ["Intersolar", "Europe", "逆变器", "展会", "户用"],
    preferredPathHints: ["news", "press", "media"],
  },
  {
    company: "天合光能",
    segment: "光伏组件",
    sourceName: "天合光能官网",
    url: "https://www.trinasolar.com/en-glb/resources/newsroom",
    keywords: ["RE+", "美国", "展会", "组件", "发布"],
    matchers: ["天合", "trina", "re+"],
    procurementKeywords: ["tender", "procurement", "招标", "采购"],
    expoKeywords: ["RE+", "美国", "展会", "组件", "发布"],
    preferredPathHints: ["news", "press", "newsroom"],
  },
  {
    company: "古瑞瓦特",
    segment: "逆变器",
    sourceName: "古瑞瓦特官网",
    url: "https://www.growatt.com/media/news",
    keywords: ["Africa", "Solar Show", "展会", "逆变器", "发布"],
    matchers: ["古瑞瓦特", "growatt", "solar show"],
    procurementKeywords: ["tender", "招标", "采购", "vendor"],
    expoKeywords: ["Africa", "Solar Show", "展会", "逆变器", "发布"],
    preferredPathHints: ["news", "media", "press"],
  },
  {
    company: "锦浪科技",
    segment: "逆变器",
    sourceName: "锦浪科技官网",
    url: "https://www.ginlong.com/news",
    keywords: ["South America", "Intersolar", "南美", "展会", "逆变器"],
    matchers: ["锦浪", "solis", "ginlong", "intersolar"],
    procurementKeywords: ["tender", "招标", "采购", "供应商"],
    expoKeywords: ["South America", "Intersolar", "南美", "展会", "逆变器"],
    preferredPathHints: ["news", "media", "press"],
  },
  {
    company: "爱旭股份",
    segment: "光伏组件/BC技术",
    sourceName: "AIKO 官网",
    url: "https://aikosolar.com/en/news/",
    keywords: ["ABC", "展会", "Intersolar", "SNEC", "组件"],
    matchers: ["爱旭", "aiko", "abc", "intersolar"],
    procurementKeywords: ["招标", "采购", "供应商", "tender", "vendor"],
    expoKeywords: ["ABC", "展会", "Intersolar", "SNEC", "组件"],
    preferredPathHints: ["news", "press", "article"],
  },
  {
    company: "华晟新能源",
    segment: "异质结/薄膜化场景",
    sourceName: "Huasun 官网",
    url: "https://www.huasunsolar.com/news/",
    keywords: ["HJT", "异质结", "招标", "展会", "组件"],
    matchers: ["华晟", "huasun", "hjt", "招标"],
    procurementKeywords: ["procurement", "招标", "中标", "采购", "shortlisted"],
    expoKeywords: ["HJT", "异质结", "展会", "Intersolar", "SNEC"],
    preferredPathHints: ["news", "article"],
  },
  {
    company: "正泰新能",
    segment: "光伏组件",
    sourceName: "Astronergy 官网",
    url: "https://www.astronergy.com/news/",
    keywords: ["ASTRO", "展会", "Intersolar", "招标", "采购"],
    matchers: ["astronergy", "正泰新能", "astro", "procurement"],
    procurementKeywords: ["procurement", "招标", "采购", "中标", "框架"],
    expoKeywords: ["Intersolar", "SNEC", "展会", "ASTRO", "exhibitor"],
    preferredPathHints: ["news", "press"],
  },
  {
    company: "阿特斯",
    segment: "光伏组件/储能",
    sourceName: "Canadian Solar IR",
    url: "https://investors.canadiansolar.com/news-releases/",
    keywords: ["storage", "module", "展会", "Intersolar", "project"],
    matchers: ["canadian solar", "阿特斯", "e-storage", "recurrent"],
    procurementKeywords: ["project", "agreement", "contract", "tender", "procurement"],
    expoKeywords: ["Intersolar", "展会", "module", "storage", "project"],
    preferredPathHints: ["news", "releases", "press"],
  },
  {
    company: "一道新能",
    segment: "光伏组件",
    sourceName: "DAS Solar 官网",
    url: "https://www.das-solar.com/en/site/news",
    keywords: ["N-Type", "展会", "Intersolar", "组件", "DBC"],
    matchers: ["das solar", "一道新能", "dbc", "n-type"],
    procurementKeywords: ["招标", "采购", "tender", "procurement"],
    expoKeywords: ["Intersolar", "SNEC", "展会", "组件", "DBC"],
    preferredPathHints: ["news", "site", "exhibitions"],
  },
  {
    company: "协鑫集成",
    segment: "光伏组件/系统集成",
    sourceName: "GCL SI 官网",
    url: "https://en.gclsi.com/news_detail/",
    keywords: ["Intersolar", "SNEC", "组件", "采购", "展会"],
    matchers: ["gcl", "协鑫", "gcl si", "intersolar"],
    procurementKeywords: ["采购", "招标", "procurement", "tender", "framework"],
    expoKeywords: ["Intersolar", "SNEC", "展会", "组件", "module"],
    preferredPathHints: ["news", "detail"],
  },
  {
    company: "First Solar",
    segment: "薄膜组件",
    sourceName: "First Solar IR",
    url: "https://investor.firstsolar.com/news/default.aspx",
    keywords: ["thin film", "CdTe", "manufacturing", "展会", "module"],
    matchers: ["first solar", "thin film", "cdte"],
    procurementKeywords: ["contract", "agreement", "supply", "procurement"],
    expoKeywords: ["module", "manufacturing", "thin film", "展会"],
    preferredPathHints: ["news", "press", "release"],
  },
  {
    company: "通威太阳能",
    segment: "光伏组件/电池片",
    sourceName: "通威官网",
    url: "https://www.tongwei.com/news/",
    keywords: ["组件", "电池片", "展会", "SNEC", "Intersolar"],
    matchers: ["通威", "tongwei", "solar", "snec"],
    procurementKeywords: ["招标", "采购", "框架", "供应商", "procurement"],
    expoKeywords: ["SNEC", "Intersolar", "展会", "组件", "电池片"],
    preferredPathHints: ["news", "article", "detail"],
  },
  {
    company: "东方日升",
    segment: "光伏组件",
    sourceName: "东方日升官网",
    url: "https://www.risenenergy.com/news/",
    keywords: ["组件", "展会", "Intersolar", "SNEC", "储能"],
    matchers: ["东方日升", "risen", "risen energy", "intersolar"],
    procurementKeywords: ["招标", "采购", "tender", "procurement"],
    expoKeywords: ["SNEC", "Intersolar", "展会", "组件", "储能"],
    preferredPathHints: ["news", "article", "press"],
  },
  {
    company: "TCL中环",
    segment: "硅片/组件",
    sourceName: "TCL中环官网",
    url: "https://www.tclzhonghuan.com/news/",
    keywords: ["硅片", "组件", "展会", "SNEC", "Intersolar"],
    matchers: ["tcl中环", "zhonghuan", "tcl", "snec"],
    procurementKeywords: ["招标", "采购", "供应商", "procurement"],
    expoKeywords: ["SNEC", "Intersolar", "展会", "硅片", "组件"],
    preferredPathHints: ["news", "detail", "article"],
  },
  {
    company: "上能电气",
    segment: "逆变器/储能",
    sourceName: "上能电气官网",
    url: "https://www.sinengsolar.com/news/",
    keywords: ["逆变器", "储能", "展会", "Intersolar", "SNEC"],
    matchers: ["上能电气", "sineng", "sineng solar", "储能"],
    procurementKeywords: ["招标", "采购", "procurement", "vendor"],
    expoKeywords: ["Intersolar", "SNEC", "展会", "逆变器", "储能"],
    preferredPathHints: ["news", "press", "article"],
  },
  {
    company: "科华数能",
    segment: "逆变器/储能",
    sourceName: "科华官网",
    url: "https://www.kehua.com/news/",
    keywords: ["逆变器", "储能", "展会", "SNEC", "欧洲"],
    matchers: ["科华", "kehua", "kehua tech", "储能"],
    procurementKeywords: ["招标", "采购", "中标", "procurement"],
    expoKeywords: ["SNEC", "展会", "逆变器", "储能", "欧洲"],
    preferredPathHints: ["news", "detail", "article"],
  },
  {
    company: "华为数字能源",
    segment: "逆变器/储能",
    sourceName: "华为数字能源官网",
    url: "https://digitalpower.huawei.com/en/news/",
    keywords: ["FusionSolar", "储能", "展会", "Intersolar", "SNEC"],
    matchers: ["华为", "huawei", "fusionsolar", "digital power"],
    procurementKeywords: ["procurement", "招标", "供应商", "vendor"],
    expoKeywords: ["FusionSolar", "SNEC", "Intersolar", "展会", "储能"],
    preferredPathHints: ["news", "article", "press"],
  },
  {
    company: "禾迈股份",
    segment: "微逆/逆变器",
    sourceName: "Hoymiles 官网",
    url: "https://www.hoymiles.com/news/",
    keywords: ["微逆", "microinverter", "展会", "Intersolar", "SNEC"],
    matchers: ["禾迈", "hoymiles", "microinverter", "intersolar"],
    procurementKeywords: ["招标", "采购", "vendor", "procurement"],
    expoKeywords: ["Intersolar", "SNEC", "展会", "微逆", "microinverter"],
    preferredPathHints: ["news", "press", "article"],
  },
  {
    company: "派能科技",
    segment: "储能电池",
    sourceName: "Pylontech 官网",
    url: "https://en.pylontech.com.cn/news.aspx",
    keywords: ["储能", "电池", "展会", "ees Europe", "SNEC"],
    matchers: ["派能", "pylontech", "battery", "ees"],
    procurementKeywords: ["招标", "采购", "tender", "procurement"],
    expoKeywords: ["ees Europe", "SNEC", "展会", "储能", "电池"],
    preferredPathHints: ["news", "detail", "press"],
  },
  {
    company: "亿纬锂能",
    segment: "储能电池",
    sourceName: "亿纬锂能官网",
    url: "https://www.evebattery.com/en/news/",
    keywords: ["储能", "电池", "展会", "论坛", "发布"],
    matchers: ["亿纬", "eve", "eve energy", "battery"],
    procurementKeywords: ["招标", "采购", "procurement", "framework"],
    expoKeywords: ["储能", "展会", "论坛", "电池", "发布"],
    preferredPathHints: ["news", "article", "detail"],
  },
  {
    company: "鹏辉能源",
    segment: "储能电池",
    sourceName: "鹏辉能源官网",
    url: "https://www.greatpower.net/news/",
    keywords: ["储能", "电池", "展会", "欧洲", "美国"],
    matchers: ["鹏辉", "great power", "鹏辉能源", "battery"],
    procurementKeywords: ["招标", "采购", "vendor", "procurement"],
    expoKeywords: ["储能", "展会", "欧洲", "美国", "电池"],
    preferredPathHints: ["news", "detail", "article"],
  },
];
